name: kt_utils
description: Useful extension methods such as forEachIndexed, roundDouble with precision etc.
version: 2.2.1
homepage: https://github.com/NijatTagizada/kt_utils
topics:
  - utils

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
